## Complete Reuters Test Set

* Tasks
    * Combine the two files of scraped data
    * Fill missing data
        * Content not available = drop
        * Decide on what to do if the title or description is missing
        * For date, take the next date (eliminates risk of peeking into the future)
    * Check the discrepancy for the overlapping data, then combine
        * From that Kaggle data there is a timespan from 2018 up to July 2020
    * Format date properly
    * Visual dipiction, articles-per-day, maybe topic mapping
    * Save for later analysis

In [1]:
import pandas as pd

In [72]:
first = pd.read_csv('../data/reuters/2021_04_11_2020_11_21.csv')
second = pd.read_csv('../data/reuters/prior_to_2020_11_21.csv')

reuters_articles = pd.concat([first, second], ignore_index=True)

In [76]:
reuters_articles.tail(5)

,Unnamed: 0,title,description,date
44001,31014,no_title,"Our apologies, the content you requested canno...",no_date
44002,31015,no_title,"Our apologies, the content you requested canno...",no_date
44003,31016,no_title,"Our apologies, the content you requested canno...",no_date
44004,31017,no_title,"Our apologies, the content you requested canno...",no_date
44005,31018,no_title,"Our apologies, the content you requested canno...",no_date

In [92]:
while 'no_title' == reuters_articles.iloc[-1]['title']:
    reuters_articles = reuters_articles.drop(reuters_articles.index[-1])
    
reuters_articles.iloc[-1]

Unnamed: 0                                                 29314
title          White House to release Obama's 2016 budget on ...
description                                       no_description
date                                                     no_date
Name: 42301, dtype: object

In [94]:
reuters_articles = reuters_articles.drop(['Unnamed: 0'], axis=1)

In [95]:
reuters_articles.tail(5)

,title,description,date
42297,Egypt deep cleans pyramids site emptied of tou...,Egypt began deep cleaning the area around the ...,Mar 25 2020
42298,Yemen's Houthi leader says Saudi-led coalition...,A leader of the Iran-aligned Yemen's Houthi mo...,Mar 25 2020
42299,"Obama touts auto bailout success, Michigan wor...","President Barack Obama, on a trip to unveil el...",no_date
42300,U.S. House fails to pass Republican bill dilut...,no_description,no_date
42301,White House to release Obama's 2016 budget on ...,no_description,no_date

In [98]:
# I'm sorry for the python sins that I am commiting I just couldn't see how I would be able to do this with zip, apply.
# For this usecase I'm not aware of a 'cythonized' method
for i in range(reuters_articles.index[-1] + 1):
    row = reuters_articles.iloc[i]
    # Take the date of the previous row -> won't accidentally date something earlier (There was news every day)
    if 'no_date' == row['date']:
        reuters_articles.iloc[i]['date'] = reuters_articles.iloc[i - 1]['date']
        
    if 'no_description' == row['description']:
        reuters_articles.iloc[i]['description'] = row['title']
        
reuters_articles.tail(3)

,title,description,date
42299,"Obama touts auto bailout success, Michigan wor...","President Barack Obama, on a trip to unveil el...",Mar 25 2020
42300,U.S. House fails to pass Republican bill dilut...,U.S. House fails to pass Republican bill dilut...,Mar 25 2020
42301,White House to release Obama's 2016 budget on ...,White House to release Obama's 2016 budget on ...,Mar 25 2020

In [102]:
# Shouldn't be the case
reuters_articles = reuters_articles.drop_duplicates(ignore_index=True)

In [103]:
reuters_articles.tail(3)

,title,description,date
42222,"Obama touts auto bailout success, Michigan wor...","President Barack Obama, on a trip to unveil el...",Mar 25 2020
42223,U.S. House fails to pass Republican bill dilut...,U.S. House fails to pass Republican bill dilut...,Mar 25 2020
42224,White House to release Obama's 2016 budget on ...,White House to release Obama's 2016 budget on ...,Mar 25 2020

In [73]:
# Headlines, Time, Description
third_party_articles = pd.read_csv('../data/kaggle/financial-news-headlines/reuters_headlines.csv')
len(third_party_articles)

32770

In [104]:
third_party_articles.head(3)

,Headlines,Time,Description
0,TikTok considers London and other locations fo...,Jul 18 2020,TikTok has been in discussions with the UK gov...
1,Disney cuts ad spending on Facebook amid growi...,Jul 18 2020,Walt Disney has become the latest company to ...
2,Trail of missing Wirecard executive leads to B...,Jul 18 2020,Former Wirecard chief operating officer Jan M...

In [106]:
third_party_articles.columns = ['title', 'date', 'description']
third_party_articles.head(3)

,title,date,description
0,TikTok considers London and other locations fo...,Jul 18 2020,TikTok has been in discussions with the UK gov...
1,Disney cuts ad spending on Facebook amid growi...,Jul 18 2020,Walt Disney has become the latest company to ...
2,Trail of missing Wirecard executive leads to B...,Jul 18 2020,Former Wirecard chief operating officer Jan M...

In [ ]:
third_party_articles = thi